# backend:
#   name: git-gateway
#   branch: main

# media_folder: "static/images"
# public_folder: "/images"

# collections:
#   - name: "blog"
#     label: "Blog"
#     folder: "content/blog"
#     create: true
#     slug: "{{slug}}"
#     fields:
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Date", name: "date", widget: "datetime" }
#       - { label: "Body", name: "body", widget: "markdown" }
